#!/bin/bash

# $IMAGE_NAME and $DOCKER_TAG are injected by docker hub into the build
# https://docs.docker.com/docker-hub/builds/advanced/

if [ -z "${IMAGE_NAME}" ]; then
  DOCKER_TAG="latest"
  IMAGE_NAME="chrisob/qpid-broker-j-docker:${DOCKER_TAG}"
fi

if [ "${DOCKER_TAG}" != "latest" ]; then
  BROKER_J_VERSION="${DOCKER_TAG}"
else
  BROKER_J_VERSION="8.0.0"
fi

docker build \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --build-arg VERSION="${DOCKER_TAG}" \
  --build-arg BROKER_J_VERSION="${BROKER_J_VERSION}" \
  --tag "${IMAGE_NAME}" \
  .
